version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.4
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: realtheone/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_value:/static
      - media_value:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: realtheone/foodgram_frontend:latest
    volumes:
      - static_value:/static
    command: cp -r /app/build/. /static/

  nginx:
    image: realtheone/foodgram_nginx:latest
    env_file: .env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_value:/static
      # - media_value:/app/media
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart:
      always
